language: node_js
node_js:
    - 12
script:
    - npm run build
deploy:
    provider: heroku
    api_key:
        secure: "B6SkARFT+JO/JaS6dtrjmV/7mT7rKxYjFuVvsca8rVXU26KjigbkEGUkd9nKPOOWyn1pnIX41PfZWNxFVjffo4xoHALKdSlNfqfQ1Yqdk44YKk0Fr1x3mBqTv8Zu4zAke5wyLESBkaqD2EibiqZ46p+B3SU0WNJFfdOl+Ar6DHEU1fVpCZx7wcIOMGSxtBP71oAhsKRL7phwlb1c4893fpIvs5aIGWli1CGi6AYh9iSv2ABNhLjH+9GEJfzH/LddHUvHE4efJETflWKo3zBSmiQR7J/QS/9Jkx18VZzNrNS7pH2pgDTr2e0Hm3UcGUMtzdI3LuUCIDxLrIY053vcmZTZflPNJHrgNhg5FyZJpJynS4XsRMB76wYijTErbmrKC4IpHCq+ncWXsuOrj27QlhRtHaBHeIy6uvMz9GPjvtpK63IxVbtoxLO0xeP6b9Yx72GdEWCqk4/TgjyQROh62h1LWhd090t2ufZ744bRaq5GtHUzMR/EHAwliWizzlclFiWJ5LsyRX3kqQJFvnUtpCROeSFncUFiPBpwDfKm7svgVYLfKGLIjY7qwFkwlphtbOJ/ZBIjwO6rj5hGcs0BrMcxDb1lwEHB6U9dLezRtj/3arYT5zUAjgP5lDtHO9xmBttQMJKna4l7qo7TaqqGJQRT1lLGmmGqxJtvcXS/U0w="
    app: dear-genie
    on:
        repo: huong-dang/dear-genie-frontend
